2017-10-09 20:53:00 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p230206/?page=13&ka=page-13, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p230206/?page=13&ka=page-13 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109efb5c0>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 20:53:17 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p230206/?page=13&ka=page-13, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p230206/?page=13&ka=page-13 (Caused by ProxyError('Cannot connect to proxy.', timeout('select timed out',)))
2017-10-09 20:53:29 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p230206/?page=13&ka=page-13, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p230206/?page=13&ka=page-13 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109f6eeb8>, 'Connection to 182.52.131.124 timed out. (connect timeout=10)'))
2017-10-09 20:53:42 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p230206/?page=13&ka=page-13, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p230206/?page=13&ka=page-13 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109ef7be0>, 'Connection to 121.31.102.157 timed out. (connect timeout=10)'))
2017-10-09 20:54:00 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p230206/?page=20&ka=page-20, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p230206/?page=20&ka=page-20 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109f7e208>, 'Connection to 105.212.61.108 timed out. (connect timeout=10)'))
2017-10-09 20:54:14 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p230206/?page=20&ka=page-20, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p230206/?page=20&ka=page-20 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 20:55:13 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p250106/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p250106/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109f7e940>, 'Connection to 101.247.67.9 timed out. (connect timeout=10)'))
2017-10-09 20:55:24 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p250106/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p250106/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109ff6710>, 'Connection to 200.84.143.163 timed out. (connect timeout=10)'))
2017-10-09 20:55:27 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p250106/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p250106/?page=7&ka=page-7 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109ff66d8>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 20:55:38 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p250106/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p250106/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109f3a470>, 'Connection to 154.72.48.214 timed out. (connect timeout=10)'))
2017-10-09 20:55:51 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p250106/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p250106/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109ff2940>, 'Connection to 171.88.42.217 timed out. (connect timeout=10)'))
2017-10-09 20:56:04 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p250106/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p250106/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109ff2630>, 'Connection to 94.247.244.107 timed out. (connect timeout=10)'))
2017-10-09 20:56:16 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p250106/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p250106/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109fa65f8>, 'Connection to 201.210.68.91 timed out. (connect timeout=10)'))
2017-10-09 20:56:28 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p250106/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p250106/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1099ed048>, 'Connection to 190.198.198.212 timed out. (connect timeout=10)'))
2017-10-09 20:56:41 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p250106/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p250106/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1099ed400>, 'Connection to 45.32.100.83 timed out. (connect timeout=10)'))
2017-10-09 20:56:53 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p250106/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p250106/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109efb4a8>, 'Connection to 110.73.28.98 timed out. (connect timeout=10)'))
2017-10-09 20:57:05 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p250106/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p250106/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1099218d0>, 'Connection to 183.89.177.51 timed out. (connect timeout=10)'))
2017-10-09 20:57:16 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=2&ka=page-2 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1099570b8>, 'Connection to 61.7.190.144 timed out. (connect timeout=10)'))
2017-10-09 20:57:28 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=2&ka=page-2 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 20:57:40 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=2&ka=page-2 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109933b00>, 'Connection to 209.222.10.142 timed out. (connect timeout=10)'))
2017-10-09 20:57:52 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=2&ka=page-2 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109933d30>, 'Connection to 176.74.154.233 timed out. (connect timeout=10)'))
2017-10-09 20:58:04 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=2&ka=page-2 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109777b70>, 'Connection to 220.143.185.248 timed out. (connect timeout=10)'))
2017-10-09 20:58:06 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=2&ka=page-2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1097776a0>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 20:58:07 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=2&ka=page-2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109185710>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 20:58:19 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=2&ka=page-2 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1099bde80>, 'Connection to 119.252.174.126 timed out. (connect timeout=10)'))
2017-10-09 20:58:34 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=2&ka=page-2 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 20:58:46 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=2&ka=page-2 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 20:58:48 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=2&ka=page-2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109aeba58>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 20:58:50 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=24&ka=page-24 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109762630>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 20:59:03 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=24&ka=page-24 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109838160>, 'Connection to 176.237.185.144 timed out. (connect timeout=10)'))
2017-10-09 20:59:06 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=24&ka=page-24 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1098382b0>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 20:59:30 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Read timed out.
2017-10-09 20:59:32 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=24&ka=page-24 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1091a9e80>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 20:59:33 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p150105/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p150105/?page=24&ka=page-24 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10971b908>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:00:04 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=3&ka=page-3, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=3&ka=page-3 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1097eff28>, 'Connection to 121.225.219.64 timed out. (connect timeout=10)'))
2017-10-09 21:00:15 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=3&ka=page-3, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=3&ka=page-3 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109768eb8>, 'Connection to 183.188.45.164 timed out. (connect timeout=10)'))
2017-10-09 21:00:19 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=3&ka=page-3, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=3&ka=page-3 (Caused by ProxyError('Cannot connect to proxy.', BrokenPipeError(32, 'Broken pipe')))
2017-10-09 21:00:21 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=3&ka=page-3, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=3&ka=page-3 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1091ce358>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:00:32 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=3&ka=page-3, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=3&ka=page-3 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10975ab38>, 'Connection to 36.68.48.49 timed out. (connect timeout=10)'))
2017-10-09 21:00:44 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=3&ka=page-3, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=3&ka=page-3 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10975ab70>, 'Connection to 18.221.40.249 timed out. (connect timeout=10)'))
2017-10-09 21:00:56 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=3&ka=page-3, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=3&ka=page-3 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109907be0>, 'Connection to 190.42.185.187 timed out. (connect timeout=10)'))
2017-10-09 21:01:11 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=3&ka=page-3, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=3&ka=page-3 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer')))
2017-10-09 21:01:26 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=3&ka=page-3, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=3&ka=page-3 (Caused by ProxyError('Cannot connect to proxy.', timeout('select timed out',)))
2017-10-09 21:01:44 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=21&ka=page-21, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=21&ka=page-21 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109907390>, 'Connection to 169.0.194.128 timed out. (connect timeout=10)'))
2017-10-09 21:01:47 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=21&ka=page-21, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=21&ka=page-21 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10975a3c8>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:02:07 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=21&ka=page-21, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=21&ka=page-21 (Caused by ProxyError('Cannot connect to proxy.', timeout('select timed out',)))
2017-10-09 21:02:19 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=21&ka=page-21, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=21&ka=page-21 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1097687f0>, 'Connection to 190.74.171.70 timed out. (connect timeout=10)'))
2017-10-09 21:02:24 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=21&ka=page-21, error is: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
2017-10-09 21:02:36 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=21&ka=page-21, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=21&ka=page-21 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1097ef7b8>, 'Connection to 121.31.158.79 timed out. (connect timeout=10)'))
2017-10-09 21:02:54 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=21&ka=page-21, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=21&ka=page-21 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 21:03:07 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=21&ka=page-21, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=21&ka=page-21 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 21:03:20 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=21&ka=page-21, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=21&ka=page-21 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer')))
2017-10-09 21:03:31 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=21&ka=page-21, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=21&ka=page-21 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1099073c8>, 'Connection to 23.88.246.18 timed out. (connect timeout=10)'))
2017-10-09 21:03:42 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p290102/?page=21&ka=page-21, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p290102/?page=21&ka=page-21 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109762cc0>, 'Connection to 124.92.216.182 timed out. (connect timeout=10)'))
2017-10-09 21:03:55 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=14&ka=page-14, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=14&ka=page-14 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10971ba90>, 'Connection to 176.237.185.129 timed out. (connect timeout=10)'))
2017-10-09 21:04:08 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=14&ka=page-14, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=14&ka=page-14 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1091e23c8>, 'Connection to 118.113.220.53 timed out. (connect timeout=10)'))
2017-10-09 21:04:12 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=14&ka=page-14, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=14&ka=page-14 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1099bde48>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:04:32 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=24&ka=page-24 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 21:04:39 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=24&ka=page-24 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109777400>: Failed to establish a new connection: [Errno 51] Network is unreachable',)))
2017-10-09 21:04:51 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=24&ka=page-24 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109933550>, 'Connection to 107.80.121.51 timed out. (connect timeout=10)'))
2017-10-09 21:04:53 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=24&ka=page-24 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1099332e8>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:05:04 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=24&ka=page-24 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10978aef0>, 'Connection to 177.92.48.251 timed out. (connect timeout=10)'))
2017-10-09 21:05:16 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=24&ka=page-24 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10978ac88>, 'Connection to 223.154.1.242 timed out. (connect timeout=10)'))
2017-10-09 21:05:29 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=24&ka=page-24 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109aa3198>, 'Connection to 190.204.252.253 timed out. (connect timeout=10)'))
2017-10-09 21:05:30 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=24&ka=page-24 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109aeb1d0>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:05:41 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=24&ka=page-24 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109aebf60>, 'Connection to 110.73.29.85 timed out. (connect timeout=10)'))
2017-10-09 21:05:54 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=24&ka=page-24 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 21:05:57 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p120118/?page=24&ka=page-24, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p120118/?page=24&ka=page-24 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1099576d8>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:06:07 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p101012/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p101012/?page=7&ka=page-7 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer')))
2017-10-09 21:06:09 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p101012/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p101012/?page=7&ka=page-7 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109ff2550>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:06:22 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p101012/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p101012/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109ff29b0>, 'Connection to 1.179.189.217 timed out. (connect timeout=10)'))
2017-10-09 21:06:34 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p101012/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p101012/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109ff65c0>, 'Connection to 201.249.115.86 timed out. (connect timeout=10)'))
2017-10-09 21:06:45 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p101012/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p101012/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109ff6748>, 'Connection to 202.154.226.69 timed out. (connect timeout=10)'))
2017-10-09 21:06:57 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p101012/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p101012/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109185b38>, 'Connection to 121.31.152.225 timed out. (connect timeout=10)'))
2017-10-09 21:07:27 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p101012/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Read timed out. (read timeout=10)
2017-10-09 21:07:31 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p101012/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p101012/?page=7&ka=page-7 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109921be0>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:07:44 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p101012/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p101012/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109f7e860>, 'Connection to 80.78.237.5 timed out. (connect timeout=10)'))
2017-10-09 21:07:56 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p101012/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p101012/?page=7&ka=page-7 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 21:08:09 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p101012/?page=7&ka=page-7, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p101012/?page=7&ka=page-7 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109f3a5c0>, 'Connection to 183.89.94.69 timed out. (connect timeout=10)'))
2017-10-09 21:08:22 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=2&ka=page-2 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109f6e4e0>, 'Connection to 197.98.11.125 timed out. (connect timeout=10)'))
2017-10-09 21:08:33 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=2&ka=page-2 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109921ba8>, 'Connection to 60.14.110.75 timed out. (connect timeout=10)'))
2017-10-09 21:08:38 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=2&ka=page-2 (Caused by ProxyError('Cannot connect to proxy.', BrokenPipeError(32, 'Broken pipe')))
2017-10-09 21:08:49 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=2&ka=page-2 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1097c29b0>, 'Connection to 80.78.71.103 timed out. (connect timeout=10)'))
2017-10-09 21:09:02 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=2&ka=page-2 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 21:09:15 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=2&ka=page-2 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109a29630>, 'Connection to 212.117.188.118 timed out. (connect timeout=10)'))
2017-10-09 21:09:18 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=2&ka=page-2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109903cf8>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:09:29 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=2&ka=page-2 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109903c88>, 'Connection to 134.35.181.205 timed out. (connect timeout=10)'))
2017-10-09 21:09:43 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=2&ka=page-2, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=2&ka=page-2 (Caused by ProxyError('Cannot connect to proxy.', timeout('select timed out',)))
2017-10-09 21:10:18 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=27&ka=page-27, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=27&ka=page-27 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 21:10:35 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=27&ka=page-27, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=27&ka=page-27 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 21:10:38 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=27&ka=page-27, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=27&ka=page-27 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1097345c0>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:11:08 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=27&ka=page-27, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Read timed out.
2017-10-09 21:11:23 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=27&ka=page-27, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=27&ka=page-27 (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-10-09 21:11:35 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=27&ka=page-27, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=27&ka=page-27 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109903940>, 'Connection to 114.243.248.243 timed out. (connect timeout=10)'))
2017-10-09 21:11:48 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=27&ka=page-27, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=27&ka=page-27 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109903780>, 'Connection to 51.254.220.25 timed out. (connect timeout=10)'))
2017-10-09 21:11:51 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=27&ka=page-27, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=27&ka=page-27 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1097c2160>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:12:02 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=27&ka=page-27, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=27&ka=page-27 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1097c2588>, 'Connection to 190.200.130.64 timed out. (connect timeout=10)'))
2017-10-09 21:12:04 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=27&ka=page-27, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=27&ka=page-27 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109f7e748>: Failed to establish a new connection: [Errno 61] Connection refused',)))
2017-10-09 21:12:16 - crawler - INFO - when crawl https://www.zhipin.com/c100010000-p220205/?page=27&ka=page-27, error is: HTTPSConnectionPool(host='www.zhipin.com', port=443): Max retries exceeded with url: /c100010000-p220205/?page=27&ka=page-27 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x109f7e7b8>, 'Connection to 37.224.15.107 timed out. (connect timeout=10)'))
